### ISSUE TITLE
how to get the correct parameters in the disp2pts function

### ISSUE THREAD

**Issue by backkon** [hahnec/plenopticam#20]
hello, I have a question I'd like to discuss with you. In your code, we can see that some parameters used in the disp2pts function are default parameters, but in fact for Illum, these parameters are not applicable, we need calibrate the LF camera, how to get the correct parameters according to the  calibration results?

**Comment by hahnec** [comment]
Heya,

The **disp2pts** function is not part of this repo, but belongs to the [depthy](https://github.com/hahnec/depthy) Python package (see [here](https://github.com/hahnec/depthy/blob/master/depthy/misc/ply_handler.py)). The idea behind these separate repos is that depth extraction algorithms may serve light-fields or stereo images from non-plenoptic cameras. So, the reason why default parameters might not be suitable in your case is simply that parameters are meant for another input source.

If it is your goal to extract depth from a Lytro camera, have you checked the [Lytro Illum Demo notebook](https://github.com/hahnec/plenopticam/blob/master/examples/04_illum_demo.ipynb)? When you follow this recipe, you are supposed to retrieve a depth map.

**Comment by backkon** [comment]
Thank you for your reply. Yes, I ran the code according to that recipe. In the depth extraction module, it first extracts the disparity map, and then extracts the depth map according to the disp2pts function in depthy, but the parameters used in the code are default and do not conform to reality . I want to know how to get the correct parameters?

**Comment by backkon** [comment]
![094209](https://user-images.githubusercontent.com/31430570/119069589-fbb72f80-ba18-11eb-889a-d2726de2b3d0.png)


Sorry, I may not express my question too clearly, there is nothing going wrong. I just want to find the right values for the parameters shown in the figure above. For example, how do I get the baseline parameters and the sensor size parameters of the illum camera, obviously the default 1 is not appropriate and needs to be adjusted according to the specific camera. The problem I care about is how to get correct values of the illum camera.

**Comment by hahnec** [comment]
While the sensor size can be found in Lytro's json-metadata file extracted by PlenoptiCam, you'll probably have a hard time determining the baseline of the Lytro camera. This is because the camera's zoom lens affects the baseline meaning it can change from one picture to another. I spent some time in my PhD developing a model that predicts the baseline of a plenoptic camera based on the focal length, pixel pitch and focus position (see [my paper](https://link.springer.com/content/pdf/10.1007%2Fs11263-017-1036-4.pdf)). In the case of Lytro cameras, however, focal length and focus position are provided as relative numbers which have to be numerically converted, e.g. to a millimeter value such as the pixel pitch from the metadata file. This can be solved experimentally by placing an object at a known distance, analyzing the disparity and plugging these values into Eq. (31) in the paper above. Hope this helps :)

**Comment by backkon** [comment]
OK, I see. Thank you for your patience~
