### ISSUE TITLE
Circle P Watermark on Custom Lightfield Image

### ISSUE THREAD

**Issue by Kelvin-Chan** [hahnec/plenopticam#7]
Hi again!

While I'm working with the v0.3.0 test version, I notice that I get a **circle P** in the export images and .gifs when I am trying to process a set of lightfield images from a custom microlens camera, which is not the case when I was processing the provided example dataset.

<img src="https://user-images.githubusercontent.com/12389998/75686650-98ea4480-5c6a-11ea-8791-cf8415a93944.jpg" alt="light" width="480" height="270" />

<img src="https://user-images.githubusercontent.com/12389998/75686425-38f39e00-5c6a-11ea-93f8-e61e754af708.png" alt="watermark" width="480" height="270" />

What would this watermark mean in particular? Does it mean a bad lightfield image, an improper calibration process, failure to decompose, or something else?  On other lightfield images tested, I also sometimes see green or black background images in the exported viewpoint stack.

<img src="https://user-images.githubusercontent.com/12389998/75688098-d8199500-5c6c-11ea-9cfb-f34ab1707f56.png" alt="greenp" width="480" height="270" />

**Comment by hahnec** [comment]
Hey Kelvin,

The translucent **P** in rendered images stands for _plenopticam_ and is kind of its signature. 

With regards to the green output image, I can only speculate that this might be related to the number of color channels in the images you provided as I have not tested monochromatic cases yet. Did you use a single channel image as input by any chance? If not, what is the major difference in the images being used?

**Comment by Kelvin-Chan** [comment]
I see - is it possible to disable the watermarking when I export the viewpoint stack? 

I've also only tested with RGB images (beyond the example datasets) at this point as well - the images collected from a prototype microlens array camera at 1080p. As for the green output image, I am unaware of any major difference that could be relevant, aside from perhaps the lighting condition and the observed object in the scene?

One thing that I realised is that if I tile the subaperture images together in order, the black/green output represents the "edges" of the subaperture view. The pixel diameter of a microlens in my custom camera is ~22 px.

Here are the Google Drive links to the [microlens calibration image](https://drive.google.com/file/d/18IO6Afmei49KybbqWuRu8f5fWBA61d17/view?usp=sharing), the [first lightfield image](https://drive.google.com/file/d/1Ep1k5lqg8EKBYMJA8WSPxNXZvGTdqSDq/view?usp=sharing), and [another lightfield image](https://drive.google.com/file/d/1ZtXeduB3zckMcPy2f8bCMYroDYDuqWPR/view?usp=sharing) that is generating the green output.

**Comment by hahnec** [comment]
Using your data, my current version (v0.3.3 ) didn't render green images, but either the mug or the light source as expected. This version is available for testing via

`pip3 install -i https://test.pypi.org/simple/ plenopticam==0.3.3`

As I wasn't able to reproduce the issue on my side, I assume that I fixed it while developing towards v0.3.2. Please let me know if this works for you.

When looking at the output images, I saw a few other problems with your data. The number of micro lenses in front of your sensor only amounts to 64x34, which yields poor quality as this corresponds to the spatial resolution of your sub-aperture images. Another thing I noted is that the micro images overlap in your photographs which may cause cross-talk in the angular domain. To further avoid unwanted cross-talk, you should also use some raw image format like *.bmp because *.jpg files imply some compression.

I think the major challenge you will be facing is the improvement of your spatial resolution. You could either get a Micro Lens Array (MLA) containing more micro lenses (smaller pitch size) or try to adjust the lateral MLA position to achieve the "focused plenoptic setup" and shift the spatio-angular resolution trade-off towards the spatial side. Yet, `plenopticam` does not support so-called "plenoptic 2.0" rendering. However, it shouldn't be too difficult to implement that since the calibration and resampling stages would be the same. It is simply the extraction part that needs to be extended. Let me know if you want to go this path and I will do my best to assist you.

There are several ways to disable the watermark process. I leave it to you to get to know the framework and circumvent this ;)

**Comment by Kelvin-Chan** [comment]
Thank you so much for the feedback! Those images were from an initial prototype assembly, so I'll definitely have to go back to the drawing board and assemble a better MLA camera - probably would be easier to improve first by going with a smaller microlens pitch or larger sensor area, for more microlenses.

Then, the downside with going for a smaller microlens pitch would be a lower angular resolution (less perspectives), which will also impact the depth estimation, is that correct? 

Are there any papers and references in particular that you recommend to learn more about the focused plenoptic setup? I can try to look into setting another assembly up in that configuration.

And that's fair about the watermark 😄  I'll dig through the code further

**Comment by hahnec** [comment]
You are right with the angular resolution trade-off. A micro image diameter of 22px is almost twice as much as the Lytro camera. For this reason, I recommend to put your MLA at a different focus position. More information on this is given in papers by Lumsdaine and Georgiev who came up with the focused setup. Let me know if you follow this path.

**Comment by Kelvin-Chan** [comment]
Closing this issue - see #8 for continued discussion on focused setup
