### ISSUE TITLE
First Launch: Failed to execute script top_level

### ISSUE THREAD

**Issue by jamesstringerparsec** [hahnec/plenopticam#9]
Hello,

I experienced this issue whenlaunching 0.5.3 for the first time on Windows, after installing.

![image](https://user-images.githubusercontent.com/38541878/87573447-32bc0680-c6cd-11ea-8936-1e47ffcfe4e0.png)

**Comment by hahnec** [comment]
Hi James, 

Thanks for raising this issue. I am having the same problem on my Windows machine. This is due to executables not being covered by the test automation. I am working on the fix.

In the meantime, you could use an earlier version instead such as [v0.5.2](https://github.com/hahnec/plenopticam/releases/tag/v0.5.2-beta), which worked for me on Win10. Will keep you posted here about the progress.

Best
Chris

**Comment by hahnec** [comment]
It turned out the error was related to write privileges on Windows. I have replaced the [Win executable](https://github.com/hahnec/plenopticam/releases/download/v0.5.3-beta/plenopticam_0.5.3.msi) in [release v0.5.3](https://github.com/hahnec/plenopticam/releases/tag/v0.5.3-beta). Can you please confirm that it is also working on your side?

**Comment by jamesstringerparsec** [comment]
Hey man,

That fixed it, not sure if you're intending to keep drawing the console window behind your GUI but the GUI is launching correctly without errors now.

I appreciate your work, there are not many actively working on light field photography especially those who are providing an easy interface to support Lytro cameras which I am a proud owner of.

I know this isn't so much in the scope of your work, but I would really enjoy some method to export gray scale depth maps from the image data.

![image](https://user-images.githubusercontent.com/38541878/87591119-26917280-c6e8-11ea-81d9-e15c70e702a4.png)

**Comment by hahnec** [comment]
Excellent! I have now added a version without the console window.

Depth map computation based on light-fields is currently left out as it is a broad research topic for all kinds of light-field sources (e.g. camera arrays) and often tackled by neural networks these days. On the contrary, plenopticam is dedicated to micro-lens based plenoptic cameras and their special requirements for light-field decomposition. With sub-aperture images from plenopticam, however, you can proceed with other tools for generic light-field depth map computation found here on GitHub that take its viewpoints as an input. Please let me know when you pick your favourite. 

On another note, may I ask what you are intending to do with your plenoptic camera? I am just interested in getting a better sense of the users' project goals.

Best 
Chris

**Comment by jamesstringerparsec** [comment]
Hey Chris, 

I just enjoy playing around with funky cameras on my spare time, and am looking for more ways to share light field images in their true form with my friends and family as it's really compelling medium, but without modern methods to visualize or share it with them other than Facebook's 3D photo functionality (where you upload a single JPEG frame along with a 2D grayscale JPEG format depth map) there aren't a lot of options out there.

Thanks for your work, I'll now close this issue.
